
FROM rayproject/ray:2.9.0-py39-cu118

USER ray

RUN pip install --no-cache-dir \
    tensorflow \
    tf-keras \ 
    mlflow \
    gymnasium \
    pygame \
    azure-storage-blob \
    fsspec

# Set up the working directory
WORKDIR /app

# Copy the training script and environment module into the container
COPY epn.py /app/epn.py
COPY data_generation.py /app/data_generation.py