
FROM rayproject/ray:2.9.0-py39-cu118

USER ray

RUN pip install --no-cache-dir \
    tensorflow \
    tf-keras \ 
    mlflow \
    gymnasium \
    pygame \
    azure-storage-blob \
    fsspec

WORKDIR /app

COPY epn.py /app/epn.py
COPY data_generation.py /app/data_generation.py