apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: ray-impala-job
  namespace: default
spec:
  entrypoint: python /app/epn.py
  shutdownAfterJobFinishes: true
  
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          nodeSelector:
            role: headnode
          containers:
            - name: ray-head
              image:
              env:
                - name: AZURE_STORAGE_CONNECTION_STRING
                  value:
                - name: TF_USE_LEGACY_KERAS 
                  value: "1"
              resources:
                limits:
                  nvidia.com/gpu: 2
                  cpu: "12"  
                  memory: "100Gi" 
                requests:
                  nvidia.com/gpu: 2
                  cpu: "12"
                  memory: "100Gi"
    workerGroupSpecs:
      - groupName: worker-group
        replicas: 30 
        minReplicas: 30
        maxReplicas: 30
        rayStartParams: {}
        template:
          spec:
            nodeSelector:
              role: worker 
            containers:
              - name: ray-worker
                image:
                env:
                  - name: AZURE_STORAGE_CONNECTION_STRING
                    value: 
                  - name: TF_USE_LEGACY_KERAS
                    value: "1"
                resources:
                  limits:
                    cpu: "1"  
                    memory: "2Gi"
                  requests:
                    cpu: "1"
                    memory: "2Gi"